name: Docker Build, Push and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  DOCKER_IMAGE_NAME: api-dominguez
  DOCKERHUB_USERNAME: ${{ secrets.USER_DH }}
  EC2_USER: ${{ secrets.USER_EC2 }}
  EC2_IP: ${{ secrets.IP_EC2 }}

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8 --max-line-length=120 --extend-ignore=E501 .

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DH }}
          password: ${{ secrets.TOKEN_DH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.USER_DH }}/${{ env.DOCKER_IMAGE_NAME }}:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLAVE_EC2 }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          cat ~/.ssh/ec2_key.pem

      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ${{ env.EC2_USER }}@${{ env.EC2_IP }} << 'EOF'
          docker pull ${{ secrets.USER_DH }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          docker stop api-container || true
          docker rm api-container || true
          docker run -d -p 8000:8000 --name api-container ${{ secrets.USER_DH }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          EOF
